# Generated by Django 3.0.7 on 2020-06-10 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionAcademica', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='Curso',
            new_name='Cursos',
        ),
    ]
